language: python

python:
  - 2.7
  #- 3.4

env:
    global:
        - BUILD=TEST

matrix:
    include:
        # Extra build to make sure that `iminuit` works without the optional dependencies
        - python: 2.7
          env: BUILD=NO_EXTRA_DEPS

        # Extra build to make sure that the docs build without errors or warnings
        - python: 2.7
          env: BUILD=DOCS

        # Extra build to compute coverage
        #- python: 2.7
        #  env: BUILD='COVERAGE'

before_install:
  - if [[ $BUILD != NO_EXTRA_DEPS ]]; then pip install IPython numpy; fi
  - if [[ $BUILD == DOCS ]]; then pip install matplotlib sphinx sphinx_rtd_theme; fi

install:
  - python setup.py build_ext -i

script:
  - if [[ $BUILD == TEST ]]; then nosetests; fi
  - if [[ $BUILD == DOCS ]]; then cd doc; sphinx-build -W -a -E -b html -d _build/doctrees . _build/html; fi
