language: python

sudo: false

matrix:
    include:
        - python: 2.7
          env: BUILD=ALL

        - python: 3.5
          env: BUILD=ALL

# See https://github.com/iminuit/iminuit/issues/270
#        - python: 3.7-dev
#          env: BUILD=TEST

        - python: 3.5
          env: BUILD=COVERAGE

        - python: 3.5
          env: BUILD=MINIMAL

        - python: 3.5
          env: BUILD=SDIST

        - python: 2.7
          env: BUILD=SDIST

# TODO: add this (travis-ci not running today, so disabling for now)
#        - python: 3.6
#          env: BUILD=CONDA

# TODO: add osx builds; (setting up multi-os envs isn't trivial, see below)
#        - os: osx
#          python: 2.7
#          env: BUILD=ALL
#
#        - os: osx
#          python: 3.5
#          env: BUILD=ALL

# TODO: add tests for conda build and install of conda package

install:
  - python .travis/install_deps.py

script:
  - make test
  - if [ $BUILD == ALL ]; then
      make test-notebooks;
      make doc;
    fi
  - if [ $BUILD == COVERAGE ]; then make coverage; fi
  - if [ $BUILD == SDIST ]; then source .travis/sdist_test.sh; fi
  - if [ $BUILD == CONDA ]; then source .travis/conda_make.sh; fi
