language: python

python:
  - 2.6
  - 2.7

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V

install:
  - python setup.py install

script:
  - mkdir empty
  - cd empty
  - nosetests iminuit

