language: python

sudo: false

matrix:
    include:
        - python: 2.7
          env: BUILD=TEST

        - python: 2.7
          env: BUILD=DOCS

        - python: 3.5
          env: BUILD=TEST

        - python: 3.5
          env: BUILD=DOCS

        - python: 3.5
          env: BUILD=COVERAGE

        - python: 3.5
          env: BUILD=NO_EXTRA_DEPS

        - python: 3.5
          env: BUILD=NO_CYTHON

        # TODO: add tests on Mac

        # TODO: add tests for Python from conda

before_install:
  - pip install setuptools Cython
  - if [[ $BUILD == NO_CYTHON ]]; then
      python setup.py sdist;
      pip uninstall -y cython;
    fi
  - if [[ $BUILD != NO_EXTRA_DEPS ]]; then pip install IPython numpy matplotlib; fi
  - if [[ $BUILD == DOCS ]]; then pip install matplotlib sphinx sphinx_rtd_theme jupyter; fi
  - if [[ $BUILD == TEST ]] || [[ $BUILD == COVERAGE ]]; then pip install pytest pytest-cov numpy; fi

install:
  - python setup.py build_ext -i
  - python setup.py install

script:
  - if [[ $BUILD == TEST ]]; then make test; fi
  - if [[ $BUILD == COVERAGE ]]; then make coverage; fi
  - if [[ $BUILD == DOCS ]]; then make doc; fi
  - if [[ $BUILD == DOCS ]]; then make test-notebooks; fi
