language: python

sudo: false

matrix:
    include:
        - python: 2.7
          env: BUILD=ALL

        - python: 3.5
          env: BUILD=ALL

# See https://github.com/iminuit/iminuit/issues/270
#        - python: 3.7-dev
#          env: BUILD=TEST

        - python: 3.5
          env: BUILD="ALL COVERAGE"

        - python: 3.5

        - python: 3.5
          env: BUILD=SDIST

        - python: 2.7
          env: BUILD=SDIST

# TODO: add this (travis-ci not running today, so disabling for now)
#        - python: 3.6
#          env: BUILD=CONDA

# TODO: add osx builds; (setting up multi-os envs isn't trivial, see below)
#        - os: osx
#          python: 2.7
#          env: BUILD=ALL
#
#        - os: osx
#          python: 3.5
#          env: BUILD=ALL

# TODO: add tests for conda build and install of conda package

before_install:
  - python .travis/install_deps.py

script:
  -| [[ $BUILD == ALL ]] && make test
  -| [[ $BUILD == ALL ]] && make test-notebooks
  -| [[ $BUILD == ALL ]] && make doc
  -| [[ $BUILD == COVERAGE ]] && make coverage
  -| [[ $BUILD == SDIST ]] && source .travis/sdist_test.sh
  -| [[ $BUILD == CONDA ]] && source .travis/conda_make.sh
